/**
 * Phase 38 Plan 38-02 — deterministic user-context string for embedding.
 *
 * Per 38-RESEARCH §Pattern 1 Option B (the locked decision): the user-context
 * vector is generated by deterministic facts-template stringification of the
 * last-30-day event summary + profile. ~150-token target per AI-SPEC §4b cost
 * table ("Embed user-context (recommender) ~150 input tokens").
 *
 * The output is a single line/paragraph (no XML fencing — embedding models
 * are sensitive to formatting; we want a natural-language description that
 * places semantically near KB / blog / community / course content embeddings).
 *
 * NEVER include drug names, dose values, or PHI identifiers (Phase 25 / D-04).
 * The recommender's embedding call is non-PHI and uses the consumer credential
 * lane — this function MUST NOT emit anything that elevates it to PHI.
 */

export interface UserContextFacts {
  goalType: 'weight_loss' | 'maintenance' | 'metabolic' | 'muscle_preservation';
  glp1Phase: 'starting' | 'escalation' | 'maintenance' | 'tapering';
  /** Number of injections in the last 30 days. */
  injectionCount: number;
  /** Net weight change over the 30-day window (in `units`). Null if no entries. */
  weightDelta30d: number | null;
  units: 'kg' | 'lb';
  /** Average mood 1-5 over the 30-day window. Null if no entries. */
  moodAvg: number | null;
  /** Top symptom names by frequency (caller pre-sorts). Caps at 5. */
  topSymptoms: string[];
  /** Current streak length in days. */
  streakDays: number;
}

const MAX_SYMPTOMS = 5;

/**
 * Returns a single-string user-context summary suitable for embedding via the
 * OpenAI / Vercel AI Gateway `/embeddings` endpoint.
 *
 * Determinism: the same `UserContextFacts` input ALWAYS produces the same
 * output string. This is critical for the AI-SPEC §5 Dim 7 eval (embedding
 * stability — same input → same vector).
 */
export function renderUserContext(f: UserContextFacts): string {
  const symptoms = f.topSymptoms.slice(0, MAX_SYMPTOMS);

  const weightDeltaPhrase =
    f.weightDelta30d === null
      ? 'no recent weight logs'
      : `weight change ${f.weightDelta30d >= 0 ? '+' : '-'}${Math.abs(f.weightDelta30d).toFixed(1)} ${f.units} over 30 days`;

  const moodPhrase =
    f.moodAvg === null ? 'mood not logged' : `mood averaging ${f.moodAvg.toFixed(1)} out of 5`;

  const symptomsPhrase =
    symptoms.length === 0
      ? 'no symptoms logged'
      : `top symptoms: ${symptoms.join(', ')}`;

  return [
    `GLP-1 user with ${f.goalType.replace(/_/g, ' ')} goal, currently in ${f.glp1Phase} phase.`,
    `${f.injectionCount} injections in the last 30 days, ${weightDeltaPhrase}.`,
    `${moodPhrase}. ${symptomsPhrase}.`,
    `Current logging streak: ${f.streakDays} day${f.streakDays === 1 ? '' : 's'}.`,
  ].join(' ');
}
