/**
 * Phase 15 Plan 08 — SEOPanel.
 *
 * Per-page SEO field editor (D-15). Slots into the page editor at the
 * page-level (NOT block-level — these fields live on the `landing_pages`
 * row, not on a `landing_page_revisions` block). The component is a thin
 * controlled-form wrapper; persistence flows through the caller's
 * `onChange(patch)` callback (the same shape the rest of the editor uses
 * for property updates).
 *
 * Design contract (15-UI-SPEC "SEO Panel Contract"):
 *   - Page title (SEO)   — Input, max 60 chars, with live character counter.
 *   - Meta description    — Textarea, max 160 chars, with live counter.
 *   - OG image            — "Choose image" button that opens AssetLibraryPicker
 *                           (15-09). Shows the selected URL when set.
 *   - Canonical URL       — Input with URL pattern; help "Leave blank to
 *                           auto-set to /{slug}".
 *   - Schema type         — Select populated from SCHEMA_TYPE_OPTIONS
 *                           (D-16: no free-text JSON-LD anywhere).
 *
 * D-16 hardline: NO free-text schema input is rendered. The structured-data
 * block on the published page is auto-generated by `generateJsonLd()` from
 * the schema type + block tree.
 */
import { useState } from 'react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input, Select, Textarea } from '@/components/ui/Input';
import { SCHEMA_TYPE_OPTIONS, type SchemaType } from '@/lib/page-builder/json-ld';
import { AssetLibraryPicker, type AssetSelection } from '../AssetLibraryPicker';

const TITLE_MAX = 60;
const DESCRIPTION_MAX = 160;
// Permissive URL pattern — accepts absolute http(s) URLs OR a leading `/`
// for site-relative canonicals. Validation is UX-only; the renderer also
// runs the value through escapeAttr.
const CANONICAL_PATTERN = /^(https?:\/\/.+|\/.*)$/;

export interface SEOFields {
  seo_title: string;
  seo_description: string;
  seo_og_image: string;
  seo_canonical: string;
  seo_schema_type: SchemaType;
}

export type SEOFieldKey = keyof SEOFields;

export interface SEOPanelProps {
  value: SEOFields;
  /**
   * Called whenever a field changes. Matches the editor's per-field update
   * shape (mirrors PropertyPanel's `onChange(field, value)` style); the
   * page-level save flow rolls these into landing_pages.seo_* columns.
   */
  onChange: (field: SEOFieldKey, value: string) => void;
}

export function SEOPanel({ value, onChange }: SEOPanelProps) {
  const [pickerOpen, setPickerOpen] = useState(false);

  const titleLen = value.seo_title.length;
  const descLen = value.seo_description.length;

  const canonicalInvalid =
    value.seo_canonical.length > 0 && !CANONICAL_PATTERN.test(value.seo_canonical);

  const handleAssetSelect = (asset: AssetSelection): void => {
    onChange('seo_og_image', asset.url);
    setPickerOpen(false);
  };

  return (
    <Card variant="flat" padding="md" className="flex flex-col gap-4">
      <header>
        <h2 className="text-[16px] font-semibold tracking-tight">SEO</h2>
        <p className="text-[12px] text-[var(--color-text-secondary)]">
          Search engines and social cards use these fields. Leave blank to
          inherit the site-wide defaults from /admin.
        </p>
      </header>

      {/* Page title (SEO) */}
      <div className="flex flex-col gap-1">
        <Input
          label="Page title (SEO)"
          hint="Distinct from the visible page heading."
          value={value.seo_title}
          maxLength={TITLE_MAX}
          onChange={(e) => onChange('seo_title', e.target.value)}
        />
        <p
          className="text-[11px] text-[var(--color-text-tertiary)] text-right"
          aria-live="polite"
        >
          {titleLen} / {TITLE_MAX}
        </p>
      </div>

      {/* Meta description */}
      <div className="flex flex-col gap-1">
        <Textarea
          label="Meta description"
          hint="The blurb under the page title in search results."
          value={value.seo_description}
          maxLength={DESCRIPTION_MAX}
          rows={3}
          onChange={(e) => onChange('seo_description', e.target.value)}
        />
        <p
          className="text-[11px] text-[var(--color-text-tertiary)] text-right"
          aria-live="polite"
        >
          {descLen} / {DESCRIPTION_MAX}
        </p>
      </div>

      {/* OG image — group is anchored on the button (the only interactive
          control). A plain <p> + <p> pair documents the field; the button's
          accessible name carries the field's label semantically. */}
      <div className="flex flex-col gap-1.5">
        <p className="text-[11px] font-semibold uppercase tracking-[0.06em] text-[var(--color-text-secondary)]">
          OG image
        </p>
        <p className="text-[12px] text-[var(--color-text-secondary)]">
          1200×630 recommended. Used for social previews on Twitter / LinkedIn /
          iMessage.
        </p>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            variant="secondary"
            size="sm"
            onClick={() => setPickerOpen(true)}
            aria-label="Choose OG image"
          >
            Choose image
          </Button>
          {value.seo_og_image ? (
            <span
              className="truncate text-[12px] text-[var(--color-text-tertiary)]"
              title={value.seo_og_image}
            >
              {value.seo_og_image}
            </span>
          ) : (
            <span className="text-[12px] text-[var(--color-text-tertiary)]">
              No image selected.
            </span>
          )}
        </div>
        <AssetLibraryPicker
          open={pickerOpen}
          onClose={() => setPickerOpen(false)}
          onSelect={handleAssetSelect}
        />
      </div>

      {/* Canonical URL */}
      <Input
        label="Canonical URL"
        hint="Leave blank to auto-set to /{slug}."
        type="url"
        value={value.seo_canonical}
        aria-invalid={canonicalInvalid || undefined}
        error={canonicalInvalid ? 'Must be an absolute URL or start with /.' : undefined}
        onChange={(e) => onChange('seo_canonical', e.target.value)}
      />

      {/* Schema type (JSON-LD) */}
      <Select
        label="JSON-LD schema type"
        hint="Auto-generated from page content. Pick the type that best fits."
        value={value.seo_schema_type}
        onChange={(e) => onChange('seo_schema_type', e.target.value as SchemaType)}
      >
        {SCHEMA_TYPE_OPTIONS.map((opt) => (
          <option key={opt} value={opt}>
            {opt}
          </option>
        ))}
      </Select>
    </Card>
  );
}
