-- Phase 38 Plan 07 — winback-scorer schema extensions (RECOMMEND-07, RECOMMEND-10).
--
-- Three additive changes scoped to this plan:
--   1. win_back_sends: add `payload jsonb default '{}'::jsonb` column to carry
--      the SAVE handoff metadata (handoff_url, reason, email_subject). The
--      Phase 40 SAVE engine reads this payload on its own cron schedule
--      (vendor-gated pattern per memory feedback_scaffolding_for_deferred_mobile_pattern).
--   2. ai_suggestion_review.status CHECK widening: add 'auto_approved_hardcoded'
--      (per memory feedback_planner_missed_status_enum_widening — status enum
--      values MUST ship in the same plan that adds the writer; otherwise the
--      INSERT throws 23514). Winback emails bypass HITL because the copy is
--      hardcoded non-AI text — the audit row records super-admin-visible
--      proof of dispatch (D-12/13 audit trail).
--   3. RPC `at_risk_users_for_winback(p_inactive_days, p_cap_days, p_limit)`:
--      pure-SQL detection (NO LLM — D-09). Selects users whose most-recent
--      logged event across {injections, weights, meals, mood} is older than
--      p_inactive_days days AND who have no win_back_sends row newer than
--      p_cap_days days (D-10 30d cap). LIMIT p_limit for batch safety.
--
-- Trust boundary (T-38-31): the 30d cap is enforced TWICE — once inside the
-- RPC's NOT EXISTS clause, and once at INSERT time via the (user_id, last_sent_at)
-- index from migration 20270705000007. Belt-and-suspenders.

begin;

-- ─── (1) win_back_sends.payload ──────────────────────────────────────────────

alter table public.win_back_sends
  add column if not exists payload jsonb not null default '{}'::jsonb;

comment on column public.win_back_sends.payload is
  'SAVE handoff metadata consumed by Phase 40 (handoff_url, reason, email_subject). Open jsonb shape per memory feedback_planner_iter1_anti_patterns.';

-- ─── (2) ai_suggestion_review.status enum widening ───────────────────────────
-- The existing CHECK constraint name in 20270705000008 is autogenerated
-- (no explicit `constraint <name>` clause). Drop by table+column inference
-- via the constraint catalog, then re-add the widened constraint.

do $$
declare
  c_name text;
begin
  select conname
    into c_name
    from pg_constraint
    where conrelid = 'public.ai_suggestion_review'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%status%'
      and pg_get_constraintdef(oid) ilike '%pending%';
  if c_name is not null then
    execute format('alter table public.ai_suggestion_review drop constraint %I', c_name);
  end if;
end $$;

alter table public.ai_suggestion_review
  add constraint ai_suggestion_review_status_chk
  check (status in (
    'pending',
    'approved',
    'rejected',
    'edited',
    'auto_approved_kb',
    'auto_approved_hardcoded'
  ));

comment on constraint ai_suggestion_review_status_chk on public.ai_suggestion_review is
  'Plan 38-07 widened to include auto_approved_hardcoded (winback non-AI copy bypasses HITL).';

-- ─── (3) RPC at_risk_users_for_winback ──────────────────────────────────────
-- SECURITY DEFINER + locked search_path per memory reference_supabase_migration_gotchas.
-- Owner = postgres role; only callable by service_role (revoke from public/anon/authenticated).

create or replace function public.at_risk_users_for_winback(
  p_inactive_days int default 14,
  p_cap_days      int default 30,
  p_limit         int default 500
)
returns table (
  user_id        uuid,
  email          text,
  timezone       text,
  last_event_at  timestamptz
)
language sql
security definer
set search_path = public, extensions
as $$
  with last_events as (
    select
      u.id as uid,
      greatest(
        coalesce((select max(created_at) from public.injections where user_id = u.id), 'epoch'::timestamptz),
        coalesce((select max(created_at) from public.weights    where user_id = u.id), 'epoch'::timestamptz),
        coalesce((select max(created_at) from public.meals      where user_id = u.id), 'epoch'::timestamptz),
        coalesce((select max(created_at) from public.mood       where user_id = u.id), 'epoch'::timestamptz)
      ) as last_at
    from auth.users u
  )
  select
    u.id          as user_id,
    u.email::text as email,
    p.timezone    as timezone,
    le.last_at    as last_event_at
  from auth.users u
  join last_events le on le.uid = u.id
  left join public.profiles p on p.id = u.id
  where le.last_at < now() - make_interval(days => p_inactive_days)
    and u.email is not null
    and not exists (
      select 1 from public.win_back_sends wbs
      where wbs.user_id = u.id
        and wbs.last_sent_at > now() - make_interval(days => p_cap_days)
    )
  limit p_limit;
$$;

comment on function public.at_risk_users_for_winback(int, int, int) is
  'Phase 38 Plan 07 — pure-SQL winback candidate detection (D-09 14d threshold + D-10 30d cap). No LLM.';

revoke all on function public.at_risk_users_for_winback(int, int, int) from public;
revoke all on function public.at_risk_users_for_winback(int, int, int) from anon;
revoke all on function public.at_risk_users_for_winback(int, int, int) from authenticated;
grant execute on function public.at_risk_users_for_winback(int, int, int) to service_role;

commit;
